name: Deploy to Azure Container Apps

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Container App
        run: |
          az containerapp create \
            --name myappbackv2 \
            --resource-group DEVOPS \
            --environment enviromentdevops \
            --image ulises647/myapp:prod \
            --cpu 1 \
            --memory 2Gi \
            --ingress external \
            --target-port 8080 \
            --registry-server index.docker.io \
            --registry-username ${{ secrets.DOCKER_USERNAME }} \
            --registry-password ${{ secrets.DOCKER_PASSWORD }}

